name: flutter_demo
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.5
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  camera: ^0.12.0+1
  path_provider: ^2.1.5
  path: ^1.9.1
  overlay_pop_up: ^1.0.6+6
  google_sign_in: ^6.2.1
  geolocator: ^13.0.0
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  test: ^1.30.0

flutter:
  assets:
    - lib/resources/images/showel_icon.png
    - lib/resources/images/camera_icon.png
    - lib/resources/images/cart_icon.png
    - lib/resources/images/flower_icon.png
    - lib/resources/images/coin.webp
    - lib/resources/images/brown.webp
    - lib/resources/images/blue.webp
    - lib/resources/images/blue.png
    - lib/resources/images/green.webp
    - lib/resources/images/mint.webp
    - lib/resources/images/pink.webp
    - lib/resources/images/purple.webp
    - lib/resources/images/yellow.webp
    - lib/resources/images/Add.webp
    - lib/resources/images/Add.png
    - lib/resources/images/ros_sticker.png
    - lib/resources/images/ros_sticker_kontur.png
    - lib/resources/images/Greenhouse.svg
    - lib/resources/images/Check.webp
    - lib/resources/images/Vitblommamedgulmitten.png
    - lib/resources/images/VBVitblommamedgulmitten.png
    - lib/resources/images/Solros.png
    - lib/resources/images/VBSolros.png
    - lib/resources/images/Tulpan.png
    - lib/resources/images/VBTulpan.png
    - lib/resources/images/Vitsippa.png
    - lib/resources/images/VBVitsippa.png
    - lib/resources/images/Calendar_v2.png
    - lib/resources/images/Expand.png
    - lib/resources/images/Identity.png
    - lib/resources/images/Social.png
    - lib/resources/images/Search.png
    - lib/resources/images/Like.png
    - lib/resources/images/SentLike.png
    - lib/resources/images/testblomma.jpg
    - lib/resources/images/Location_v2.png
    - lib/resources/images/BluePot_smaller.png
    - lib/resources/images/Avatar_Blue.png
    - lib/resources/images/Avatar_Green.png
    - lib/resources/images/Avatar_Pink.png
    - lib/resources/images/Avatar_Purple.png
    - lib/resources/images/Avatar_Red.png
    - lib/resources/images/Avatar_Yellow.png



  uses-material-design: true