spring.application.name=user-service
server.port=8082
 
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://mysql.dsv.su.se:3306/alba2774
spring.datasource.username=alba2774
spring.datasource.password=uPhi1miephah
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jackson.serialization.indent-output=true
 
management.endpoints.web.exposure.include=health,info