spring.application.name=auth-service
server.port=8081

google.client-id=167485843554-b82rj6jet7kr9rt81r0qm20jv40okesd.apps.googleusercontent.com
jwt.secret=ettlångtslumpmässigthemligtnyckel123456

# URL of user-service (no trailing slash)
user-service.url=https://group-1-75.pvt.dsv.su.se/user

management.endpoints.web.exposure.include=health,info
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration