spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mariadb://mysql.dsv.su.se:3306/arhe4293
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.datasource.username=arhe4293
spring.datasource.password=Phe5chi9geen