spring.application.name=demo
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://mysql.dsv.su.se:3306/arhe4293
spring.datasource.username=arhe4293
spring.datasource.password=Phe5chi9geen
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jackson.serialization.indent-output=true